#!/usr/bin/env bash

MOFED=0
GDS=0
DOCKER_OPTIONS=()
CMD=""
if [ $# -eq 0 ] ; then
        CMD=help
else
        while [[ $# -gt 0 ]]; do
          opt="$1"

          case $opt in
            run)
              CMD="$1"
              shift
              ;;
            --enable-mofed)
              MOFED="1"
              shift
              ;;
            --enable-gds)
              GDS="1"
              shift
              ;;
            --enable-gds-compat)
              GDS_COMPAT="1"
              shift
              ;;
            -h | --help | help)
              CMD="help"
              DOCKER_OPTIONS+=" $1"
              shift
              ;;

            *) # unknown option
              DOCKER_OPTIONS+=" $1"
              shift
              ;;
          esac
        done
fi

if [ "x$MOFED" = "x1" ]; then
	uverbs=$(ls /dev/infiniband/uverbs* 2>&1)
	if [ $? -eq 0 ] ; then
		MOFED_OPTS=" --net host --cap-add=IPC_LOCK -e NVIDIA_MOFED=enabled "
	fi
fi

if [ "x$GDS" = "x1" ] ; then
	nvfs_devs=$(ls /dev/nvidia-fs* 2>&1)
	if [ $? -eq 0 ] ; then
		GDS_OPTS=" --ipc host  -e NVIDIA_GDS=enabled "
	fi
	GDS_OPTS="${NVFS_DEPS} ${NVFS_DEVS}"
elif [ "x$GDS_COMPAT" = "x1" ] ; then
	NVFS_DEPS=" --ipc host  --volume /run/udev:/run/udev:ro "
	GDS_OPTS="${NVFS_DEPS}"
fi


if [ "$CMD" = "run" ] ;then
	echo exec docker " run --runtime=nvidia ${GDS_OPTS} ${MOFED_OPTS} ${DOCKER_OPTIONS}"
	exec docker run --runtime=nvidia ${GDS_OPTS} ${MOFED_OPTS} ${DOCKER_OPTIONS}
elif [ "$CMD" = "help" ] ; then

      echo "Note: "`basename $0`" is a wrapper script around docker to provide GDS specific flags and device(s)"
      echo
      echo "GPUDirect Storage Options:"
      echo " 	--enable-gds         pass nvidia_fs character device(s) and flags"
      echo " 	--enable-gds-compat  allow for GDS to work in compat mode only"
      echo " 	--enable-mofed pass  mellanox character device(s) and flags"
      echo
      docker ${DOCKER_OPTIONS}
else
	exec docker ${DOCKER_OPTIONS}
fi
